---
-
  hosts: servers
  tasks:
  - name: Install apache packages
    yum:
      name: apache2
      state: present
  - name: ensure httpd is running
    service:
      name: apache2
      state: started
